export const EVENTS = [
  {
    key: 'mehndi',
    name: 'Mehndi',
    date: 'Friday, August 15',
    time: 'Evening',
    location: '42 Lisson Crescent',
    dressCode: 'Colourful Indian Attire',
    description: 'An intimate evening of mehndi, music, and celebration. Detailed schedule coming soon.',
  },
  {
    key: 'pithi',
    name: 'Pithi & Grah Shanti',
    date: 'Saturday, August 16',
    time: 'Afternoon',
    location: 'TBA',
    dressCode: 'Traditional Indian Attire',
    description: 'Detailed schedule coming soon.',
  },
  {
    key: 'sangeet',
    name: 'Sangeet',
    date: 'Saturday, August 16',
    time: '6:30 PM onwards',
    location: 'Chandni Gateway',
    dressCode: 'Festive Indian Attire',
    description: 'An evening of music, dance, and celebration. Detailed schedule coming soon.',
  },
  {
    key: 'wedding',
    name: 'Wedding',
    date: 'Sunday, August 17',
    time: '3:30 PM onwards',
    location: 'Terrace on the Green',
    dressCode: 'Formal Indian Attire',
    description: 'The big day! Detailed schedule coming soon.',
  },
]
